package AT4_Ramos;

import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 * This class represents the GUI for adding a student.
 * It allows users to input a username and password, which will be stored in a JSON file.
 */
public class Addstudent extends javax.swing.JFrame {
    /**
     * Creates new form Addstudents
     */
    
    public Addstudent() {
        initComponents();
    }
    /**
     * Initializes the GUI components. This method is auto-generated by NetBeans.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addtxt1 = new javax.swing.JTextField();
        passtxt1 = new javax.swing.JPasswordField();
        bck = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        clr = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 95, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 148, -1, -1));
        jPanel1.add(addtxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 91, 156, 30));

        passtxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passtxt1ActionPerformed(evt);
            }
        });
        jPanel1.add(passtxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 144, 156, 30));

        bck.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bck.setText("Back");
        bck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckActionPerformed(evt);
            }
        });
        jPanel1.add(bck, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 260, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 203, -1, -1));

        clr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clr.setText("Clear");
        clr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrActionPerformed(evt);
            }
        });
        jPanel1.add(clr, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 203, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ADD STUDENT");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 31, 183, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AT4_Ramos/bg.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // GUI component initialization
    
    private void passtxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passtxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passtxt1ActionPerformed
    /**
     * Handles the event when the password field is used.
     */
    
    /**
     * Handles the event when the 'Back' button is clicked.
     * Navigates back to the welcome screen.
     */
    private void bckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckActionPerformed
        welcome m = new welcome();
        m.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_bckActionPerformed
    /**
     * Handles the event when the 'Clear' button is clicked.
     * Clears the username and password fields.
     */
    private void clrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrActionPerformed
        addtxt1.setText("");
        passtxt1.setText("");
    }//GEN-LAST:event_clrActionPerformed
    
    /**
     * Handles the event when the 'Add' button is clicked.
     * Validates input and adds a new student to the JSON file.
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
     String username = addtxt1.getText().trim();
    String password = new String(passtxt1.getPassword()).trim();
    
    // Validate input fields
    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Invalid Input!");
        return;
    }                                        

    String filePath = "src\\AT4_Ramos\\user.json"; 
    JSONParser parser = new JSONParser();

     try (FileReader reader = new FileReader(filePath)) {
            JSONObject jsonObject = (JSONObject) parser.parse(reader);
            JSONArray usersArray = (JSONArray) jsonObject.get("users");

        // Check if username already exists
        for (Object obj : usersArray) {
            JSONObject user = (JSONObject) obj;
            if (user.get("username").equals(username)) {
                JOptionPane.showMessageDialog(this, "Error");
                return;
            }
        }
    
        // Add new student
        JSONObject newUser = new JSONObject();
        newUser.put("username", username);
        newUser.put("password", password);
        usersArray.add(newUser);

        // Write back to the file
        try (FileWriter file = new FileWriter(filePath)) {
            jsonObject.put("users", usersArray);
            file.write(jsonObject.toJSONString());
            file.flush();
        }

        JOptionPane.showMessageDialog(this, "Student added successfully!");
        addtxt1.setText("");
        passtxt1.setText("");    
     } catch (IOException e) {
    JOptionPane.showMessageDialog(this, "File not found or unreadable!", "Error", JOptionPane.ERROR_MESSAGE);
    e.printStackTrace();
    } catch (ParseException e) {
    JOptionPane.showMessageDialog(this, "Error parsing JSON file!", "Error", JOptionPane.ERROR_MESSAGE);
    e.printStackTrace();
}   
    
    }                                        

    /**
     * The main method to run the Addstudent form.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addstudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addtxt1;
    private javax.swing.JButton bck;
    private javax.swing.JButton clr;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passtxt1;
    // End of variables declaration//GEN-END:variables
}
